- name: Deploy contrail for kubernetes
  hosts: localhost
  tasks:
  - name: Run deploy contrail script
    command: ./tools/deploy-for_k8s.sh
    when:
      - should_deploy is defined
      - should_deploy == "yes"
